In [5]:
import pandas as pd
import os

In [ ]:
def split_functie_csv(filepath, tijd_column="Time (s)"):
    df = pd.read_csv(filepath)
    map_output = filepath + "_split"
    os.makedirs(map_output, exist_ok=True)
    df['second'] = df[tijd_column].astype(int)
    for second, group in df.groupby('second'):
        output_file = map_output + f"/second_{second}.csv"
        group.drop(columns=['second'], inplace=True)
        group.to_csv(output_file, index=False)
        print(f"Saved {second}.csv with {len(group)} rows.")

In [13]:
for i in ['Asfalt', 'Brug', 'Gras', 'Stenen']:
    for j in [0, 0.5, 1, 1.5, 2]:
        split_functie_csv(f"{i} {j}\Raw Data.csv")

<>:3: SyntaxWarning: invalid escape sequence '\R'
<>:3: SyntaxWarning: invalid escape sequence '\R'
C:\Users\doris\AppData\Local\Temp\ipykernel_41348\3535144234.py:3: SyntaxWarning: invalid escape sequence '\R'
  split_functie_csv(f"{i} {j}\Raw Data.csv")

Saved 0.csv with 99 rows.
Saved 1.csv with 100 rows.
Saved 2.csv with 99 rows.
Saved 3.csv with 100 rows.
Saved 4.csv with 99 rows.
Saved 5.csv with 100 rows.
Saved 6.csv with 99 rows.
Saved 7.csv with 100 rows.
Saved 8.csv with 100 rows.
Saved 9.csv with 99 rows.
Saved 10.csv with 100 rows.
Saved 11.csv with 99 rows.
Saved 12.csv with 100 rows.
Saved 13.csv with 99 rows.
Saved 14.csv with 100 rows.
Saved 15.csv with 89 rows.
Saved 0.csv with 100 rows.
Saved 1.csv with 99 rows.
Saved 2.csv with 100 rows.
Saved 3.csv with 99 rows.
Saved 4.csv with 100 rows.
Saved 5.csv with 99 rows.
Saved 6.csv with 100 rows.
Saved 7.csv with 99 rows.
Saved 8.csv with 100 rows.
Saved 9.csv with 99 rows.
Saved 10.csv with 100 rows.
Saved 11.csv with 99 rows.
Saved 12.csv with 100 rows.
Saved 13.csv with 99 rows.
Saved 14.csv with 26 rows.
Saved 0.csv with 100 rows.
Saved 1.csv with 100 rows.
Saved 2.csv with 99 rows.
Saved 3.csv with 100 rows.
Saved 4.csv with 99 rows.
Saved 5.csv with 100 rows.
Saved 6.csv with 99 rows.
Saved 7.csv with 100 rows.
Saved 8.csv with 99 rows.
Saved 9.csv with 100 rows.
Saved 10.csv with 99 rows.
Saved 11.csv with 100 rows.
Saved 12.csv with 99 rows.
Saved 13.csv with 49 rows.
Saved 0.csv with 100 rows.
Saved 1.csv with 100 rows.
Saved 2.csv with 99 rows.
Saved 3.csv with 100 rows.
Saved 4.csv with 99 rows.
Saved 5.csv with 100 rows.
Saved 6.csv with 99 rows.
Saved 7.csv with 100 rows.
Saved 8.csv with 99 rows.
Saved 9.csv with 100 rows.
Saved 10.csv with 99 rows.
Saved 11.csv with 100 rows.
Saved 12.csv with 99 rows.
Saved 13.csv with 49 rows.
Saved 0.csv with 100 rows.
Saved 1.csv with 99 rows.
Saved 2.csv with 100 rows.
Saved 3.csv with 99 rows.
Saved 4.csv with 100 rows.
Saved 5.csv with 99 rows.
Saved 6.csv with 100 rows.
Saved 7.csv with 100 rows.
Saved 8.csv with 99 rows.
Saved 9.csv with 100 rows.
Saved 10.csv with 99 rows.
Saved 11.csv with 100 rows.
Saved 12.csv with 99 rows.
Saved 13.csv with 100 rows.
Saved 14.csv with 13 rows.
Saved 0.csv with 100 rows.
Saved 1.csv with 100 rows.
Saved 2.csv with 99 rows.
Saved 3.csv with 100 rows.
Saved 4.csv with 99 rows.
Saved 5.csv with 100 rows.
Saved 6.csv with 99 rows.
Saved 7.csv with 100 rows.
Saved 8.csv with 99 rows.
Saved 9.csv with 100 rows.
Saved 10.csv with 99 rows.
Saved 11.csv with 100 rows.
Saved 12.csv with 99 rows.
Saved 13.csv with 100 rows.
Saved 14.csv with 87 rows.
Saved 0.csv with 100 rows.
Saved 1.csv with 100 rows.
Saved 2.csv with 99 rows.
Saved 3.csv with 100 rows.
Saved 4.csv with 99 rows.
Saved 5.csv with 100 rows.
Saved 6.csv with 99 rows.
Saved 7.csv with 100 rows.
Saved 8.csv with 100 rows.
Saved 9.csv with 99 rows.
Saved 10.csv with 100 rows.
Saved 11.csv with 99 rows.
Saved 12.csv with 100 rows.
Saved 13.csv with 99 rows.
Saved 14.csv with 100 rows.
Saved 15.csv with 99 rows.
Saved 16.csv with 100 rows.
Saved 17.csv with 16 rows.
Saved 0.csv with 100 rows.
Saved 1.csv with 100 rows.
Saved 2.csv with 99 rows.
Saved 3.csv with 100 rows.
Saved 4.csv with 99 rows.
Saved 5.csv with 100 rows.
Saved 6.csv with 99 rows.
Saved 7.csv with 100 rows.
Saved 8.csv with 99 rows.
Saved 9.csv with 100 rows.
Saved 10.csv with 99 rows.
Saved 11.csv with 100 rows.
Saved 12.csv with 99 rows.
Saved 13.csv with 100 rows.
Saved 14.csv with 99 rows.
Saved 15.csv with 67 rows.
Saved 0.csv with 100 rows.
Saved 1.csv with 100 rows.
Saved 2.csv with 99 rows.
Saved 3.csv with 100 rows.
Saved 4.csv with 99 rows.
Saved 5.csv with 100 rows.
Saved 6.csv with 99 rows.
Saved 7.csv with 100 rows.
Saved 8.csv with 100 rows.
Saved 9.csv with 99 rows.
Saved 10.csv with 100 rows.
Saved 11.csv with 99 rows.
Saved 12.csv with 100 rows.
Saved 13.csv with 99 rows.
Saved 14.csv with 100 rows.
Saved 15.csv with 99 rows.
Saved 16.csv with 100 rows.
Saved 17.csv with 16 rows.
Saved 0.csv with 100 rows.
Saved 1.csv with 100 rows.
Saved 2.csv with 99 rows.
Saved 3.csv with 100 rows.
Saved 4.csv with 99 rows.
Saved 5.csv with 100 rows.
Saved 6.csv with 99 rows.
Saved 7.csv with 100 rows.
Saved 8.csv with 99 rows.
Saved 9.csv with 100 rows.
Saved 10.csv with 99 rows.
Saved 11.csv with 100 rows.
Saved 12.csv with 99 rows.
Saved 13.csv with 100 rows.
Saved 14.csv with 100 rows.
Saved 15.csv with 73 rows.
Saved 0.csv with 100 rows.
Saved 1.csv with 99 rows.
Saved 2.csv with 100 rows.
Saved 3.csv with 99 rows.
Saved 4.csv with 100 rows.
Saved 5.csv with 99 rows.
Saved 6.csv with 100 rows.
Saved 7.csv with 99 rows.
Saved 8.csv with 100 rows.
Saved 9.csv with 99 rows.
Saved 10.csv with 100 rows.
Saved 11.csv with 99 rows.
Saved 12.csv with 100 rows.
Saved 13.csv with 99 rows.
Saved 14.csv with 69 rows.
Saved 0.csv with 100 rows.
Saved 1.csv with 99 rows.
Saved 2.csv with 100 rows.
Saved 3.csv with 99 rows.
Saved 4.csv with 100 rows.
Saved 5.csv with 99 rows.
Saved 6.csv with 100 rows.
Saved 7.csv with 100 rows.
Saved 8.csv with 99 rows.
Saved 9.csv with 100 rows.
Saved 10.csv with 99 rows.
Saved 11.csv with 100 rows.
Saved 12.csv with 99 rows.
Saved 13.csv with 100 rows.
Saved 14.csv with 83 rows.
Saved 0.csv with 100 rows.
Saved 1.csv with 100 rows.
Saved 2.csv with 99 rows.
Saved 3.csv with 100 rows.
Saved 4.csv with 99 rows.
Saved 5.csv with 100 rows.
Saved 6.csv with 99 rows.
Saved 7.csv with 100 rows.
Saved 8.csv with 99 rows.
Saved 9.csv with 100 rows.
Saved 10.csv with 99 rows.
Saved 11.csv with 100 rows.
Saved 12.csv with 99 rows.
Saved 13.csv with 65 rows.
Saved 0.csv with 100 rows.
Saved 1.csv with 99 rows.
Saved 2.csv with 100 rows.
Saved 3.csv with 99 rows.
Saved 4.csv with 100 rows.
Saved 5.csv with 99 rows.
Saved 6.csv with 100 rows.
Saved 7.csv with 99 rows.
Saved 8.csv with 100 rows.
Saved 9.csv with 99 rows.
Saved 10.csv with 100 rows.
Saved 11.csv with 99 rows.
Saved 12.csv with 100 rows.
Saved 13.csv with 99 rows.
Saved 14.csv with 82 rows.
Saved 0.csv with 100 rows.
Saved 1.csv with 99 rows.
Saved 2.csv with 100 rows.
Saved 3.csv with 99 rows.
Saved 4.csv with 100 rows.
Saved 5.csv with 99 rows.
Saved 6.csv with 100 rows.
Saved 7.csv with 99 rows.
Saved 8.csv with 100 rows.
Saved 9.csv with 99 rows.
Saved 10.csv with 100 rows.
Saved 11.csv with 99 rows.
Saved 12.csv with 100 rows.
Saved 13.csv with 35 rows.
Saved 0.csv with 100 rows.
Saved 1.csv with 100 rows.
Saved 2.csv with 99 rows.
Saved 3.csv with 100 rows.
Saved 4.csv with 99 rows.
Saved 5.csv with 100 rows.
Saved 6.csv with 99 rows.
Saved 7.csv with 100 rows.
Saved 8.csv with 99 rows.
Saved 9.csv with 100 rows.
Saved 10.csv with 99 rows.
Saved 11.csv with 100 rows.
Saved 12.csv with 99 rows.
Saved 13.csv with 52 rows.
Saved 0.csv with 100 rows.
Saved 1.csv with 100 rows.
Saved 2.csv with 99 rows.
Saved 3.csv with 100 rows.
Saved 4.csv with 99 rows.
Saved 5.csv with 100 rows.
Saved 6.csv with 99 rows.
Saved 7.csv with 100 rows.
Saved 8.csv with 99 rows.
Saved 9.csv with 100 rows.
Saved 10.csv with 99 rows.
Saved 11.csv with 100 rows.
Saved 12.csv with 99 rows.
Saved 13.csv with 100 rows.
Saved 14.csv with 40 rows.
Saved 0.csv with 100 rows.
Saved 1.csv with 99 rows.
Saved 2.csv with 100 rows.
Saved 3.csv with 99 rows.
Saved 4.csv with 100 rows.
Saved 5.csv with 99 rows.
Saved 6.csv with 100 rows.
Saved 7.csv with 99 rows.
Saved 8.csv with 100 rows.
Saved 9.csv with 99 rows.
Saved 10.csv with 100 rows.
Saved 11.csv with 99 rows.
Saved 12.csv with 100 rows.
Saved 13.csv with 99 rows.
Saved 14.csv with 100 rows.
Saved 15.csv with 99 rows.
Saved 16.csv with 70 rows.
Saved 0.csv with 100 rows.
Saved 1.csv with 99 rows.
Saved 2.csv with 100 rows.
Saved 3.csv with 99 rows.
Saved 4.csv with 100 rows.
Saved 5.csv with 99 rows.
Saved 6.csv with 100 rows.
Saved 7.csv with 99 rows.
Saved 8.csv with 100 rows.
Saved 9.csv with 99 rows.
Saved 10.csv with 100 rows.
Saved 11.csv with 99 rows.
Saved 12.csv with 100 rows.
Saved 13.csv with 99 rows.
Saved 14.csv with 100 rows.
Saved 15.csv with 99 rows.
Saved 16.csv with 27 rows.
Saved 0.csv with 99 rows.
Saved 1.csv with 100 rows.
Saved 2.csv with 99 rows.
Saved 3.csv with 100 rows.
Saved 4.csv with 99 rows.
Saved 5.csv with 100 rows.
Saved 6.csv with 99 rows.
Saved 7.csv with 100 rows.
Saved 8.csv with 99 rows.
Saved 9.csv with 100 rows.
Saved 10.csv with 100 rows.
Saved 11.csv with 99 rows.
Saved 12.csv with 100 rows.
Saved 13.csv with 99 rows.
Saved 14.csv with 100 rows.
Saved 15.csv with 99 rows.
Saved 16.csv with 70 rows.

In [16]:
def split_functie_csv(filepath, tijd_column="Time (s)"):
    df = pd.read_csv(filepath)
    #map_output = filepath + "_split" ## andere naam
    #os.makedirs(map_output, exist_ok=True)
    df['second'] = df[tijd_column].astype(int)
    for second, group in df.groupby('second'):
        output_file = f"{i}_{j}_second_{second}.csv"
        group.drop(columns=['second'], inplace=True)
        group.to_csv(output_file, index=False)
        print(f"Saved {second}.csv with {len(group)} rows.")

In [30]:
metadata = []

for i in ['Asfalt', 'Brug', 'Gras', 'Stenen']:
    for j in [0, 0.5, 1, 1.5, 2]:
        filepath = f"{i} {j}\Raw Data.csv"
        df = pd.read_csv(filepath)
        #map_output = filepath + "_split" ## andere naam
        #os.makedirs(map_output, exist_ok=True)
        df['second'] = df['Time (s)'].astype(int)
        for second, group in df.groupby('second'):
            output_file = f"{i}_{j}_second_{second}.csv"
            group.drop(columns=['second'], inplace=True)
            group.to_csv(output_file, index=False)
            print(f"Saved {second}.csv with {len(group)} rows.")
            
            metadata.append({
            "cut_file": f"{i}_{j}_second_{second}.csv",
            "road_types": i,
            "backpack_weight": j,
            'weather (degrees)': '11'
        })
            ## weart

<>:5: SyntaxWarning: invalid escape sequence '\R'
<>:5: SyntaxWarning: invalid escape sequence '\R'
C:\Users\doris\AppData\Local\Temp\ipykernel_41348\1676656952.py:5: SyntaxWarning: invalid escape sequence '\R'
  filepath = f"{i} {j}\Raw Data.csv"

Saved 0.csv with 99 rows.
Saved 1.csv with 100 rows.
Saved 2.csv with 99 rows.
Saved 3.csv with 100 rows.
Saved 4.csv with 99 rows.
Saved 5.csv with 100 rows.
Saved 6.csv with 99 rows.
Saved 7.csv with 100 rows.
Saved 8.csv with 100 rows.
Saved 9.csv with 99 rows.
Saved 10.csv with 100 rows.
Saved 11.csv with 99 rows.
Saved 12.csv with 100 rows.
Saved 13.csv with 99 rows.
Saved 14.csv with 100 rows.
Saved 15.csv with 89 rows.
Saved 0.csv with 100 rows.
Saved 1.csv with 99 rows.
Saved 2.csv with 100 rows.
Saved 3.csv with 99 rows.
Saved 4.csv with 100 rows.
Saved 5.csv with 99 rows.
Saved 6.csv with 100 rows.
Saved 7.csv with 99 rows.
Saved 8.csv with 100 rows.
Saved 9.csv with 99 rows.
Saved 10.csv with 100 rows.
Saved 11.csv with 99 rows.
Saved 12.csv with 100 rows.
Saved 13.csv with 99 rows.
Saved 14.csv with 26 rows.
Saved 0.csv with 100 rows.
Saved 1.csv with 100 rows.
Saved 2.csv with 99 rows.
Saved 3.csv with 100 rows.
Saved 4.csv with 99 rows.
Saved 5.csv with 100 rows.
Saved 6.csv with 99 rows.
Saved 7.csv with 100 rows.
Saved 8.csv with 99 rows.
Saved 9.csv with 100 rows.
Saved 10.csv with 99 rows.
Saved 11.csv with 100 rows.
Saved 12.csv with 99 rows.
Saved 13.csv with 49 rows.
Saved 0.csv with 100 rows.
Saved 1.csv with 100 rows.
Saved 2.csv with 99 rows.
Saved 3.csv with 100 rows.
Saved 4.csv with 99 rows.
Saved 5.csv with 100 rows.
Saved 6.csv with 99 rows.
Saved 7.csv with 100 rows.
Saved 8.csv with 99 rows.
Saved 9.csv with 100 rows.
Saved 10.csv with 99 rows.
Saved 11.csv with 100 rows.
Saved 12.csv with 99 rows.
Saved 13.csv with 49 rows.
Saved 0.csv with 100 rows.
Saved 1.csv with 99 rows.
Saved 2.csv with 100 rows.
Saved 3.csv with 99 rows.
Saved 4.csv with 100 rows.
Saved 5.csv with 99 rows.
Saved 6.csv with 100 rows.
Saved 7.csv with 100 rows.
Saved 8.csv with 99 rows.
Saved 9.csv with 100 rows.
Saved 10.csv with 99 rows.
Saved 11.csv with 100 rows.
Saved 12.csv with 99 rows.
Saved 13.csv with 100 rows.
Saved 14.csv with 13 rows.
Saved 0.csv with 100 rows.
Saved 1.csv with 100 rows.
Saved 2.csv with 99 rows.
Saved 3.csv with 100 rows.
Saved 4.csv with 99 rows.
Saved 5.csv with 100 rows.
Saved 6.csv with 99 rows.
Saved 7.csv with 100 rows.
Saved 8.csv with 99 rows.
Saved 9.csv with 100 rows.
Saved 10.csv with 99 rows.
Saved 11.csv with 100 rows.
Saved 12.csv with 99 rows.
Saved 13.csv with 100 rows.
Saved 14.csv with 87 rows.
Saved 0.csv with 100 rows.
Saved 1.csv with 100 rows.
Saved 2.csv with 99 rows.
Saved 3.csv with 100 rows.
Saved 4.csv with 99 rows.
Saved 5.csv with 100 rows.
Saved 6.csv with 99 rows.
Saved 7.csv with 100 rows.
Saved 8.csv with 100 rows.
Saved 9.csv with 99 rows.
Saved 10.csv with 100 rows.
Saved 11.csv with 99 rows.
Saved 12.csv with 100 rows.
Saved 13.csv with 99 rows.
Saved 14.csv with 100 rows.
Saved 15.csv with 99 rows.
Saved 16.csv with 100 rows.
Saved 17.csv with 16 rows.
Saved 0.csv with 100 rows.
Saved 1.csv with 100 rows.
Saved 2.csv with 99 rows.
Saved 3.csv with 100 rows.
Saved 4.csv with 99 rows.
Saved 5.csv with 100 rows.
Saved 6.csv with 99 rows.
Saved 7.csv with 100 rows.
Saved 8.csv with 99 rows.
Saved 9.csv with 100 rows.
Saved 10.csv with 99 rows.
Saved 11.csv with 100 rows.
Saved 12.csv with 99 rows.
Saved 13.csv with 100 rows.
Saved 14.csv with 99 rows.
Saved 15.csv with 67 rows.
Saved 0.csv with 100 rows.
Saved 1.csv with 100 rows.
Saved 2.csv with 99 rows.
Saved 3.csv with 100 rows.
Saved 4.csv with 99 rows.
Saved 5.csv with 100 rows.
Saved 6.csv with 99 rows.
Saved 7.csv with 100 rows.
Saved 8.csv with 100 rows.
Saved 9.csv with 99 rows.
Saved 10.csv with 100 rows.
Saved 11.csv with 99 rows.
Saved 12.csv with 100 rows.
Saved 13.csv with 99 rows.
Saved 14.csv with 100 rows.
Saved 15.csv with 99 rows.
Saved 16.csv with 100 rows.
Saved 17.csv with 16 rows.
Saved 0.csv with 100 rows.
Saved 1.csv with 100 rows.
Saved 2.csv with 99 rows.
Saved 3.csv with 100 rows.
Saved 4.csv with 99 rows.
Saved 5.csv with 100 rows.
Saved 6.csv with 99 rows.
Saved 7.csv with 100 rows.
Saved 8.csv with 99 rows.
Saved 9.csv with 100 rows.
Saved 10.csv with 99 rows.
Saved 11.csv with 100 rows.
Saved 12.csv with 99 rows.
Saved 13.csv with 100 rows.
Saved 14.csv with 100 rows.
Saved 15.csv with 73 rows.
Saved 0.csv with 100 rows.
Saved 1.csv with 99 rows.
Saved 2.csv with 100 rows.
Saved 3.csv with 99 rows.
Saved 4.csv with 100 rows.
Saved 5.csv with 99 rows.
Saved 6.csv with 100 rows.
Saved 7.csv with 99 rows.
Saved 8.csv with 100 rows.
Saved 9.csv with 99 rows.
Saved 10.csv with 100 rows.
Saved 11.csv with 99 rows.
Saved 12.csv with 100 rows.
Saved 13.csv with 99 rows.
Saved 14.csv with 69 rows.
Saved 0.csv with 100 rows.
Saved 1.csv with 99 rows.
Saved 2.csv with 100 rows.
Saved 3.csv with 99 rows.
Saved 4.csv with 100 rows.
Saved 5.csv with 99 rows.
Saved 6.csv with 100 rows.
Saved 7.csv with 100 rows.
Saved 8.csv with 99 rows.
Saved 9.csv with 100 rows.
Saved 10.csv with 99 rows.
Saved 11.csv with 100 rows.
Saved 12.csv with 99 rows.
Saved 13.csv with 100 rows.
Saved 14.csv with 83 rows.
Saved 0.csv with 100 rows.
Saved 1.csv with 100 rows.
Saved 2.csv with 99 rows.
Saved 3.csv with 100 rows.
Saved 4.csv with 99 rows.
Saved 5.csv with 100 rows.
Saved 6.csv with 99 rows.
Saved 7.csv with 100 rows.
Saved 8.csv with 99 rows.
Saved 9.csv with 100 rows.
Saved 10.csv with 99 rows.
Saved 11.csv with 100 rows.
Saved 12.csv with 99 rows.
Saved 13.csv with 65 rows.
Saved 0.csv with 100 rows.
Saved 1.csv with 99 rows.
Saved 2.csv with 100 rows.
Saved 3.csv with 99 rows.
Saved 4.csv with 100 rows.
Saved 5.csv with 99 rows.
Saved 6.csv with 100 rows.
Saved 7.csv with 99 rows.
Saved 8.csv with 100 rows.
Saved 9.csv with 99 rows.
Saved 10.csv with 100 rows.
Saved 11.csv with 99 rows.
Saved 12.csv with 100 rows.
Saved 13.csv with 99 rows.
Saved 14.csv with 82 rows.
Saved 0.csv with 100 rows.
Saved 1.csv with 99 rows.
Saved 2.csv with 100 rows.
Saved 3.csv with 99 rows.
Saved 4.csv with 100 rows.
Saved 5.csv with 99 rows.
Saved 6.csv with 100 rows.
Saved 7.csv with 99 rows.
Saved 8.csv with 100 rows.
Saved 9.csv with 99 rows.
Saved 10.csv with 100 rows.
Saved 11.csv with 99 rows.
Saved 12.csv with 100 rows.
Saved 13.csv with 35 rows.
Saved 0.csv with 100 rows.
Saved 1.csv with 100 rows.
Saved 2.csv with 99 rows.
Saved 3.csv with 100 rows.
Saved 4.csv with 99 rows.
Saved 5.csv with 100 rows.
Saved 6.csv with 99 rows.
Saved 7.csv with 100 rows.
Saved 8.csv with 99 rows.
Saved 9.csv with 100 rows.
Saved 10.csv with 99 rows.
Saved 11.csv with 100 rows.
Saved 12.csv with 99 rows.
Saved 13.csv with 52 rows.
Saved 0.csv with 100 rows.
Saved 1.csv with 100 rows.
Saved 2.csv with 99 rows.
Saved 3.csv with 100 rows.
Saved 4.csv with 99 rows.
Saved 5.csv with 100 rows.
Saved 6.csv with 99 rows.
Saved 7.csv with 100 rows.
Saved 8.csv with 99 rows.
Saved 9.csv with 100 rows.
Saved 10.csv with 99 rows.
Saved 11.csv with 100 rows.
Saved 12.csv with 99 rows.
Saved 13.csv with 100 rows.
Saved 14.csv with 40 rows.
Saved 0.csv with 100 rows.
Saved 1.csv with 99 rows.
Saved 2.csv with 100 rows.
Saved 3.csv with 99 rows.
Saved 4.csv with 100 rows.
Saved 5.csv with 99 rows.
Saved 6.csv with 100 rows.
Saved 7.csv with 99 rows.
Saved 8.csv with 100 rows.
Saved 9.csv with 99 rows.
Saved 10.csv with 100 rows.
Saved 11.csv with 99 rows.
Saved 12.csv with 100 rows.
Saved 13.csv with 99 rows.
Saved 14.csv with 100 rows.
Saved 15.csv with 99 rows.
Saved 16.csv with 70 rows.
Saved 0.csv with 100 rows.
Saved 1.csv with 99 rows.
Saved 2.csv with 100 rows.
Saved 3.csv with 99 rows.
Saved 4.csv with 100 rows.
Saved 5.csv with 99 rows.
Saved 6.csv with 100 rows.
Saved 7.csv with 99 rows.
Saved 8.csv with 100 rows.
Saved 9.csv with 99 rows.
Saved 10.csv with 100 rows.
Saved 11.csv with 99 rows.
Saved 12.csv with 100 rows.
Saved 13.csv with 99 rows.
Saved 14.csv with 100 rows.
Saved 15.csv with 99 rows.
Saved 16.csv with 27 rows.
Saved 0.csv with 99 rows.
Saved 1.csv with 100 rows.
Saved 2.csv with 99 rows.
Saved 3.csv with 100 rows.
Saved 4.csv with 99 rows.
Saved 5.csv with 100 rows.
Saved 6.csv with 99 rows.
Saved 7.csv with 100 rows.
Saved 8.csv with 99 rows.
Saved 9.csv with 100 rows.
Saved 10.csv with 100 rows.
Saved 11.csv with 99 rows.
Saved 12.csv with 100 rows.
Saved 13.csv with 99 rows.
Saved 14.csv with 100 rows.
Saved 15.csv with 99 rows.
Saved 16.csv with 70 rows.

In [32]:
metadata = pd.DataFrame(metadata)
metadata.head()

                cut_file road_types  backpack_weight weather (degrees)
0  Asfalt_0_second_0.csv     Asfalt              0.0                11
1  Asfalt_0_second_1.csv     Asfalt              0.0                11
2  Asfalt_0_second_2.csv     Asfalt              0.0                11
3  Asfalt_0_second_3.csv     Asfalt              0.0                11
4  Asfalt_0_second_4.csv     Asfalt              0.0                11

In [36]:
metadata['road_types'] = metadata['road_types'].replace({
    'Asfalt': 'Asphalts',
    'Brug': 'Wood',
    'Gras': 'Grass',
    'Stenen': 'Bricks'
})
metadata.head()

                cut_file road_types  backpack_weight weather (degrees)
0  Asfalt_0_second_0.csv   Asphalts              0.0                11
1  Asfalt_0_second_1.csv   Asphalts              0.0                11
2  Asfalt_0_second_2.csv   Asphalts              0.0                11
3  Asfalt_0_second_3.csv   Asphalts              0.0                11
4  Asfalt_0_second_4.csv   Asphalts              0.0                11